classdef  CocosimMenu    
    methods(Static)
        %% Define the custom menu function.
        function schemaFcns = cocosimMenu
            schemaFcns = {@getcocoSim};
        end

        %% Define the custom menu function.
        function schema = getcocoSim(callbackInfo)
            schema = sl_container_schema;
            schema.label = 'CoCoSim';
            schema.statustip = 'Automated Analysis Framework';
            schema.autoDisableWhen = 'Busy';

            modelWorkspace = get_param(callbackInfo.studio.App.blockDiagramHandle,'modelworkspace');
            if modelWorkspace.hasVariable('cocomSimMenuDisabled') && ...
                    modelWorkspace.getVariable('cocomSimMenuDisabled') == 1
                schema.state = 'Disabled';
            end

            schema.childrenFcns = {...
                @VerificationMenu.verify, ...
                @VerificationMenu.verifyUsing,...
                @ValidationMenu.validate, ...
                @UnsupportedBlocksMenu.checkUnsupportedBlocks, ...
                @ViewContractMenu.viewContract, ...
                @PropertyGenerationMenu.generateProperty, ...
                @PreprocessingMenu.preprocess,...
                @CocosimWindowMenu.getCompiler, ...
                @PreferencesMenu.getMenu ...
                };
        end
    end
end