function [ S ] = masked_subsystems_struct( file_name, mask_type )
%Non supporté : 'Coulombic and Viscous Friction',...
%    'Dead Zone Dynamic', 'Rate Limiter Dynamic',
%    'Wrap To Zero', 'Difference', 'Discrete Derivative',...
%    'First-Order Hold', 'Tapped Delay Line', 'First Order Transfer Fcn',...
%    'Lead or Lag Compensator', 'Transfer Fcn Real Zero', 'Bit Clear',...
%    'Bit Set', 'Detect Change', 'Detect Decrease',...
%    'Detect Fall Negative', 'Detect Fall Nonpositive', 'Detect Increase',...
%    'Detect Rise Nonnegative', 'Detect Rise Positive', 'Extract Bits',...
%    'Interval Test', 'Interval Test Dynamic', 'Cosine',...
%    'Lookup Table Dynamic', 'Sine', 'Algebraic Constraint',...
%    'MinMax Running Resettable', 'Slider Gain', 'Squeeze', 'Checks_DGap',...
%    'Checks_DRange', 'Checks_SGap', 'Checks_SRange', 'Checks_Gradient',...
%    'Checks_DMin', 'Checks_DMax', 'Checks_Resolution', 'Checks_SMin',...
%    'Checks_SMax', 'Block Support Table', 'DocBlock', 'CMBlock',...
%    'Timed Linearization', 'Triggered Linearization',...
%    'Function-Call Generator', 'Conversion Inherited',...
%    'Data Type Propagation', 'Scaling Strip', 'Environment Controller',...
%    'Manual Switch', 'XY scope', 'Band-Limited White Noise', 'chirp',...
%    'Counter Free-Running', 'Counter Limited', 'Ramp', 'Repeating table',...
%    'Repeating Sequence Interpolated', 'Repeating Sequence Stair',...
%    'Sigbuilder block', 'Stateflow', 'S-Function Builder',...
%    'Fixed-Point State-Space', 'Transfer Fcn Direct Form II',...
%    'Transfer Fcn Direct Form II Time Varying', 'Unit Delay Enabled',...
%    'Unit Delay Enabled External Initial Condition',...
%    'Unit Delay Enabled Resettable',...
%    'Unit Delay Enabled Resettable External Initial Condition',...
%    'Unit Delay External Initial Condition', 'Unit Delay Resettable',...
%    'Unit Delay Resettable External Initial Condition',...
%    'Unit Delay With Preview Enabled',...
%    'Unit Delay With Preview Enabled Resettable',...
%    'Unit Delay With Preview Enabled Resettable External RV',...
%    'Unit Delay With Preview Resettable',...
%    'Unit Delay With Preview Resettable External RV',...
%    'Real World Value Decrement', 'Stored Integer Value Decrement',...
%    'Decrement Time To Zero', 'Decrement To Zero',...
%    'Real World Value Increment', 'Stored Integer Value Increment'

S = struct();

% vérifier ce que MaskType renvoit
if strcmp(mask_type, 'Bitwise Operator')
    S.logicop = get_param(file_name, 'logicop');
    S.BitMask = get_param(file_name, 'BitMask');
    S.UseBitMask = get_param(file_name, 'UseBitMask');
    S.NumInputPorts = get_param(file_name, 'NumInputPorts');
    S.BitMaskRealWorld = get_param(file_name, 'BitMaskRealWorld');
elseif strcmp(mask_type, 'Saturation Dynamic')
    S.OutMin = get_param(file_name, 'OutMin');
    S.OutMax = get_param(file_name, 'OutMax');
elseif strcmp(mask_type, 'Compare To Constant') | strcmp(mask_type, 'Compare To Zero')
    S.relop = get_param(file_name, 'relop');
    S.const = get_param(file_name, 'const'); %n'existe pas pour Zero
    S.OutDataTypeStr = get_param(file_name, 'OutDataTypeStr');
end

end

