% Arrangement of the Simulink blocks with the different libraries
% TODO : attention, différencier les doubles dans le code (Concatenate, Outport, Inport, Sin)
% + doubles d'une meme librairie

global Continuous Discontinuities Discrete Logic_and_Bit_Operations...
    Lookup_Tables Math_Operation Model_Verification Model_Wide_Utilities...
    Ports_and_Subsystems Signal_Attributes Signal_Routing Sinks Sources...
    User_Defined_Function Additional_Discrete Additional_Math...
    Masked_SubSystem

Continuous = {'Derivative', 'Integrator', 'SecondOrderIntegrator',...
    'StateSpace', 'TransferFcn', 'TransportDelay', 'VariableTimeDelay',...
    'VariableTransportDelay', 'ZeroPole'};

Discontinuities = {'Backlash', 'DeadZone', 'HitCrossing', 'Quantizer',...
    'RateLimiter', 'Relay', 'Saturate'};

Discrete = {'Delay', 'DiscreteFilter', 'DiscreteFIR',...
    'DiscreteStateSpace', 'DiscreteTransferFcn', 'DiscreteZeroPole',...
    'DiscreteIntegrator', 'Enabled Delay', 'Memory', 'UnitDelay',...
    'ZeroOrderHold'};

Logic_and_Bit_Operations = {'CombinatorialLogic', 'Logic',...
    'RelationalOperator', 'ArithShift'};

Lookup_Tables = {'Lookup_n-D', 'LookupNDDirect', 'Interpolation_n-D',...
    'PreLookup'};

Math_Operation = {'Abs', 'Sum', 'Assignment',...
    'Bias', 'ComplexToMagnitudeAngle', 'ComplexToRealImag',...
    'Product', 'DotProduct', 'Find', 'Gain',...
    'MagnitudeAngleToComplex', 'Math', 'Concatenate',...
    'MinMax', 'PermuteDimensions', 'Polyval', 'Product',...
    'RealImagToComplex', 'Sqrt', 'Reshape',...
    'Rounding', 'Signum', 'Sin',...
    'Trigonometry', 'UnaryMinus', 'SampleTimeMath'};

Model_Verification = {'Assertion'};

Model_Wide_Utilities = {};

Ports_and_Subsystems = {'ActionPort', 'SubSystem',...
    'EnablePort', 'ForEach', 'ForIterator',...
    'If', 'Inport', 'ModelReference', 'Outport',...
    'Subsystem', 'Subsystem Examples',...
    'SwitchCase', 'TriggerPort', 'WhileIterator'};

Signal_Attributes = {'BusToVector', 'DataTypeConversion',...
    'DataTypeDuplicate', 'InitialCondition', 'Probe', 'RateTransition',...
    'SignalConversion', 'SignalSpecification', 'SampleTimeMath', 'Width'};

Signal_Routing = {'BusAssignment', 'BusCreator', 'BusSelector',...
    'DataStoreMemory', 'DataStoreRead', 'DataStoreWrite', 'Demux',...
    'From', 'Goto', 'GotoTagVisibility',...
    'MultiPortSwitch', 'Merge', 'Mux', 'VariantSink',...
    'Selector', 'Switch', 'Concatenate', 'tVariantSource'};

Sinks = {'Display', 'Scope', 'Outport',...
    'Stop Simulation', 'Terminator', 'ToFile', 'ToWorkspace'};

Sources = {'Clock', 'Constant',...
    'DigitalClock', 'EnumeratedConstant', 'FromFile',...
    'FromWorkspace', 'Ground', 'Inport', 'DiscretePulseGenerator',...
    'RandomNumber',...
    'SignalGenerator', 'Sin', 'Step',...
    'UniformRandomNumber', 'WaveformGenerator'};

User_Defined_Function = {'Fcn', 'MATLABFcn', 'M-S-Function',...
    'MATLABSystem', 'S-Function'};

Additional_Discrete = {};

Additional_Math = {};

Masked_SubSystem = {'Coulombic and Viscous Friction',...
    'Dead Zone Dynamic', 'Rate Limiter Dynamic', 'Saturation Dynamic',...
    'Wrap To Zero', 'Difference', 'Discrete Derivative',...
    'First-Order Hold', 'Tapped Delay Line', 'First Order Transfer Fcn',...
    'Lead or Lag Compensator', 'Transfer Fcn Real Zero', 'Bit Clear',...
    'Bit Set', 'Bitwise Operator', 'Compare To Constant',...
    'Compare To Zero', 'Detect Change', 'Detect Decrease',...
    'Detect Fall Negative', 'Detect Fall Nonpositive', 'Detect Increase',...
    'Detect Rise Nonnegative', 'Detect Rise Positive', 'Extract Bits',...
    'Interval Test', 'Interval Test Dynamic', 'Cosine',...
    'Lookup Table Dynamic', 'Sine', 'Algebraic Constraint',...
    'MinMax Running Resettable', 'Slider Gain', 'Squeeze', 'Checks_DGap',...
    'Checks_DRange', 'Checks_SGap', 'Checks_SRange', 'Checks_Gradient',...
    'Checks_DMin', 'Checks_DMax', 'Checks_Resolution', 'Checks_SMin',...
    'Checks_SMax', 'Block Support Table', 'DocBlock', 'CMBlock',...
    'Timed Linearization', 'Triggered Linearization',...
    'Function-Call Generator', 'Conversion Inherited',...
    'Data Type Propagation', 'Scaling Strip', 'Environment Controller',...
    'Manual Switch', 'XY scope', 'Band-Limited White Noise', 'chirp',...
    'Counter Free-Running', 'Counter Limited', 'Ramp', 'Repeating table',...
    'Repeating Sequence Interpolated', 'Repeating Sequence Stair',...
    'Sigbuilder block', 'Stateflow', 'S-Function Builder',...
    'Fixed-Point State-Space', 'Transfer Fcn Direct Form II',...
    'Transfer Fcn Direct Form II Time Varying', 'Unit Delay Enabled',...
    'Unit Delay Enabled External Initial Condition',...
    'Unit Delay Enabled Resettable',...
    'Unit Delay Enabled Resettable External Initial Condition',...
    'Unit Delay External Initial Condition', 'Unit Delay Resettable',...
    'Unit Delay Resettable External Initial Condition',...
    'Unit Delay With Preview Enabled',...
    'Unit Delay With Preview Enabled Resettable',...
    'Unit Delay With Preview Enabled Resettable External RV',...
    'Unit Delay With Preview Resettable',...
    'Unit Delay With Preview Resettable External RV',...
    'Real World Value Decrement', 'Stored Integer Value Decrement',...
    'Decrement Time To Zero', 'Decrement To Zero',...
    'Real World Value Increment', 'Stored Integer Value Increment'};
