#include <assert.h>
#include "Copy_of_safe_1_PP.h"

/* C code generated by lustrec
   Version number 1.4-535
   Code is C99 compliant
   Using (double) floating-point numbers */
   
/* Import dependencies */

/* Global constants (definitions) */

/* Struct definitions */
struct Copy_of_safe_1_PP_mem {struct _arrow_mem *ni_0;
                              };


void Copy_of_safe_1_PP_reset (struct Copy_of_safe_1_PP_mem *self) {
  
  _arrow_reset(self->ni_0);
  return;
}

void Copy_of_safe_1_PP_step (double In1_1_1, double In2_1_1, 
                             double (*Out1_1_1), double (*Out2_2_1),
                             struct Copy_of_safe_1_PP_mem *self) {
  double Abs_1_1;
  double Switch_1_1;
  _Bool __Copy_of_safe_1_PP_1;
  double i_virtual_local;
  
  
  
  
  
  _arrow_step (1, 0, &__Copy_of_safe_1_PP_1, self->ni_0);
  if (__Copy_of_safe_1_PP_1) {
    i_virtual_local = 0.0;
  } else {
    i_virtual_local = 1.0;
  }
  if ((In1_1_1 >= In2_1_1)) {
    Switch_1_1 = In1_1_1;
  } else {
    Switch_1_1 = In2_1_1;
  }
  if ((Switch_1_1 >= 0.0)) {
    Abs_1_1 = Switch_1_1;
  } else {
    Abs_1_1 = (- Switch_1_1);
  }
  *Out2_2_1 = Abs_1_1;
  *Out1_1_1 = Switch_1_1;
  
  
  
  
  return;
}

