#include <stdio.h>
#include <unistd.h>
#include "/home/shizue/internship/cocosim2-stdlib/tools/verifiers/linux/include/lustrec/io_frontend.h"
#include <stdlib.h>
#include <assert.h>
#include "Copy_of_safe_1_PP_alloc.h"

/* C code generated by lustrec
   Version number 1.4-535
   Code is C99 compliant
   Using (double) floating-point numbers */
   
int main (int argc, char *argv[]) {
  /* Declaration of inputs/outputs variables */
  double In1_1_1;
  FILE *f_in1;
  f_in1 = fopen("Copy_of_safe_1_PP_Copy_of_safe_1_PP_simu.in1", "w");
  double In2_1_1;
  FILE *f_in2;
  f_in2 = fopen("Copy_of_safe_1_PP_Copy_of_safe_1_PP_simu.in2", "w");
  double Out1_1_1;
  FILE *f_out1;
  f_out1 = fopen("Copy_of_safe_1_PP_Copy_of_safe_1_PP_simu.out1", "w");
  double Out2_2_1;
  FILE *f_out2;
  f_out2 = fopen("Copy_of_safe_1_PP_Copy_of_safe_1_PP_simu.out2", "w");
  
  /* Main memory allocation */
  Copy_of_safe_1_PP_ALLOC(static,main_mem);
  
  /* Initialize the main memory */
  Copy_of_safe_1_PP_reset(&main_mem);
  
  ISATTY = isatty(0);
  
  /* Infinite loop */
  while(1){
    fflush(stdout);
    fflush(f_in1);
    fflush(f_in2);
    fflush(f_out1);
    fflush(f_out2);
    
    In1_1_1 = _get_double(f_in1, "In1_1_1");
    In2_1_1 = _get_double(f_in2, "In2_1_1");
    Copy_of_safe_1_PP_step (In1_1_1, In2_1_1, &Out1_1_1, &Out2_2_1, &main_mem);
    _put_double(f_out1, "Out1_1_1", Out1_1_1);
    _put_double(f_out2, "Out2_2_1", Out2_2_1);
  }
  
  
  return 1;
}
