/* C code generated by lustrec
   Version number 1.4-535
   Code is C99 compliant
   Using (double) floating-point numbers */
   
#ifndef _COPY_OF_SAFE_1_PP_alloc
#define _COPY_OF_SAFE_1_PP_alloc

/* Import header from Copy_of_safe_1_PP */
#include "Copy_of_safe_1_PP.h"

/* Import dependencies */

/* Struct definitions */
struct Copy_of_safe_1_PP_mem {struct _arrow_mem *ni_0;
                              };

/* Node allocation function/macro prototypes */
#define Copy_of_safe_1_PP_DECLARE(attr, inst)\
  attr struct Copy_of_safe_1_PP_mem inst;\
  _arrow_DECLARE(attr, inst ## _ni_0);
  
#define Copy_of_safe_1_PP_LINK(inst) do {\
  _arrow_LINK(inst ## _ni_0);\
  inst.ni_0 = &inst ## _ni_0;\
} while (0)

#define Copy_of_safe_1_PP_ALLOC(attr, inst)\
  Copy_of_safe_1_PP_DECLARE(attr, inst);\
  Copy_of_safe_1_PP_LINK(inst);



#endif

