/* C code generated by lustrec
   Version number 1.4-535
   Code is C99 compliant
   Using (double) floating-point numbers */
   
#ifndef _COPY_OF_SAFE_1_PP
#define _COPY_OF_SAFE_1_PP

/* Imports standard library */
#include "/home/shizue/internship/cocosim2-stdlib/tools/verifiers/linux/include/lustrec/arrow.h"


/* Import dependencies */

/* Types definitions */

/* Global constant (declarations, definitions are in C file) */

/* Structs declarations */
struct Copy_of_safe_1_PP_mem;

/* Nodes declarations */
extern void Copy_of_safe_1_PP_reset (struct Copy_of_safe_1_PP_mem *self);

extern void Copy_of_safe_1_PP_init (struct Copy_of_safe_1_PP_mem *self);

extern void Copy_of_safe_1_PP_clear (struct Copy_of_safe_1_PP_mem *self);

extern void Copy_of_safe_1_PP_step (double In1_1_1, double In2_1_1, 
                                    double (*Out1_1_1), double (*Out2_2_1),
                                    struct Copy_of_safe_1_PP_mem *self);


#endif

